#!/usr/bin/env python3
"""Generate assets/images/SPRITES.md from the per-object atlas index.

The atlases are named after what they hold, so the file tree is already the
first level of navigation; this adds the second one -- a single table of all
264 sprite names with their atlas and size, so "where is star-gray" is one
grep rather than a directory listing.

Run from the repo root:  python tools/sprite_index.py
"""
import os
import re
import sys

IMAGES = os.path.join("assets", "images")
INDEX = os.path.join(IMAGES, "sprites", "index.xml")
ATLAS = re.compile(r'<atlas file="([^"]+)" width="(\d+)" height="(\d+)"')
SPRITE = re.compile(r'<sprite name="([^"]+)" x="(\d+)" y="(\d+)" '
                    r'width="(\d+)" height="(\d+)"')


def main() -> int:
    if not os.path.isfile(INDEX):
        print("missing %s -- run from the repo root" % INDEX, file=sys.stderr)
        return 1

    atlases = []          # (file, w, h, [(name, x, y, w, h)])
    with open(INDEX, encoding="utf-8") as f:
        for line in f:
            m = ATLAS.search(line)
            if m:
                atlases.append((m.group(1), int(m.group(2)),
                                int(m.group(3)), []))
                continue
            m = SPRITE.search(line)
            if m:
                atlases[-1][3].append(
                    (m.group(1), int(m.group(2)), int(m.group(3)),
                     int(m.group(4)), int(m.group(5))))

    total = sum(len(a[3]) for a in atlases)
    lines = [
        "# Sprite index",
        "",
        "Generated by `tools/sprite_index.py` from "
        "`assets/images/sprites/index.xml` — do not edit by hand.",
        "",
        "One atlas per object. `SpriteBank` (`src/core/sprite_bank.gd`) resolves",
        "a sprite name against all of them, so no loader names an atlas.",
        "",
        f"{total} sprites in {len(atlases)} atlases.",
        "",
        "## Atlases",
        "",
        "| atlas | frames | canvas |",
        "| --- | --- | --- |",
    ]
    for file, w, h, rows in atlases:
        lines.append("| `%s` | %d | %d x %d |" % (file, len(rows), w, h))

    lines += ["", "## Sprites", "", "| sprite | atlas | x, y | w x h |",
              "| --- | --- | --- | --- |"]
    flat = sorted((name, file, x, y, w, h)
                  for file, _, _, rows in atlases
                  for name, x, y, w, h in rows)
    for name, file, x, y, w, h in flat:
        lines.append("| `%s` | %s | %d, %d | %d x %d |"
                     % (name, file, x, y, w, h))

    out = os.path.join(IMAGES, "SPRITES.md")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %s: %d sprites, %d atlases" % (out, total, len(atlases)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
